# T1-12
---
주어진 데이터에서 상위 10개 국가의 접종률 평균과 하위 10개 국가의   접종률 평균을 구하고, 그 차이를 구해보세요   
(단, 100%가 넘는 접종률 제거, 소수 첫째자리까지 출력)

In [1]:
import pandas as pd

df = pd.read_csv("./covid-vaccination-vs-death_ratio.csv")
df.head()

,Unnamed: 0,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,New_deaths,population,ratio
0,0,Afghanistan,AFG,2021-05-11,504502.0,448878.0,55624.0,12,40295077.0,1.113977
1,1,Afghanistan,AFG,2021-05-20,547901.0,470341.0,77560.0,10,40295077.0,1.167242
2,2,Afghanistan,AFG,2021-05-24,573277.0,476367.0,96910.0,10,40295077.0,1.182197
3,3,Afghanistan,AFG,2021-05-26,590454.0,479372.0,111082.0,19,40295077.0,1.189654
4,4,Afghanistan,AFG,2021-05-27,593313.0,479574.0,113739.0,14,40295077.0,1.190155

In [6]:
country_ratio= df.groupby('country').max() # 가장 큰값 = 마지막날 = 최종 접종률
country_ratio

,Unnamed: 0,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,New_deaths,population,ratio
country,,,,,,,,,
Afghanistan,19,AFG,2021-11-27,5228706.0,4397449.0,3566192.0,86,40295077.0,10.913117
Albania,181,ALB,2021-12-23,2286235.0,1131547.0,1018549.0,18,2870177.0,39.424293
Algeria,196,DZA,2021-12-14,12437324.0,7019879.0,5554702.0,34,44996174.0,15.601058
Andorra,220,AND,2021-12-12,115709.0,56628.0,50551.0,2,77355.0,73.205352
Angola,258,AGO,2021-12-23,11164918.0,7423668.0,3741250.0,18,34472807.0,21.534852
...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,26282,WLF,2021-11-30,11939.0,6016.0,5923.0,0,11094.0,54.227510
Yemen,26293,YEM,2021-12-02,786027.0,556652.0,366587.0,10,30824630.0,1.805868
Zambia,26363,ZMB,2021-11-11,985443.0,806611.0,626900.0,72,19191260.0,4.203012
Zimbabwe,26622,ZWE,2021-12-26,7214640.0,4103288.0,3111352.0,170,15209563.0,26.978343
"occupied Palestinian territory, including east Jerusalem",18489,PSE,2021-12-20,3315774.0,2053044.0,1478705.0,34,5283006.0,38.861285

In [20]:
# 정렬
top = country_ratio.sort_values('ratio',ascending=False)
bottom = country_ratio.sort_values('ratio')
top['ratio'].head()

country
Gibraltar               122.149682
Malta                    99.307358
United Arab Emirates     98.484635
Cuba                     91.873382
Brunei Darussalam        91.328883
Name: ratio, dtype: float64

In [21]:
# 이상치 제거 및 접종률만 추출
top = top['ratio'].iloc[1:]
bottom = bottom['ratio']

In [22]:
top10 = top.iloc[:10].mean()
bottom10 = bottom.iloc[:10].mean()
top10,bottom10

(90.34726740770431, 1.9129097691393402)

In [24]:
print(round(top10-bottom10,1))

88.4